In [6]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.datasets.mnist import load_data


In [132]:
# load the data
(X_train, y_train_un), (X_test, y_test) = load_data(path='mnist.npz');

print(X_test.shape);
print(y_test.shape);
# plt.figure(figsize=(10, 10));
# for i in range(0,100):
#     plt.subplot(10, 10, i+1);
#     plt.imshow(X_train[i], cmap="gray");
#     plt.title(y_train[i], pad=-1)
#     plt.axis('off');
# plt.show();

(10000, 28, 28)
(10000,)


In [57]:
# change the data
y_train = np.zeros((len(y_train_un), 10));
for i in range(len(y_train_un)):
    tmp = np.zeros(10);
    tmp[y_train_un[i]] = 1;
    y_train[i] = tmp
X_train = X_train.reshape((60000, 1, -1))[:, 0, :];
print(X_train.shape)
print(y_train)

(60000, 784)
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [87]:
# making the model
model = Sequential(layers = [
    Dense(784, activation = 'relu'),
    Dense(1176, activation = 'relu'),
    Dense(823, activation = 'relu'),
    Dense(494, activation = 'relu'),
    Dense(197, activation = 'relu'),
    Dense(78, activation = 'relu'),
    Dense(23, activation = 'relu'),
    Dense(10, activation = 'linear')
]);


In [91]:
model.compile(loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True), optimizer=tf.keras.optimizers.Adam());

In [92]:
model.fit(X_train, y_train, epochs=10);

Epoch 1/10
1875/1875 [==============================] - 49s 25ms/step - loss: 2.1262
Epoch 2/10
1875/1875 [==============================] - 49s 26ms/step - loss: 0.6455
Epoch 3/10
1875/1875 [==============================] - 48s 25ms/step - loss: 0.2314
Epoch 4/10
1875/1875 [==============================] - 51s 27ms/step - loss: 0.1538
Epoch 5/10
1875/1875 [==============================] - 49s 26ms/step - loss: 0.1272
Epoch 6/10
1875/1875 [==============================] - 50s 27ms/step - loss: 0.1038
Epoch 7/10
1875/1875 [==============================] - 49s 26ms/step - loss: 0.1168
Epoch 8/10
1875/1875 [==============================] - 49s 26ms/step - loss: 0.0868
Epoch 9/10
1875/1875 [==============================] - 51s 27ms/step - loss: 0.0779
Epoch 10/10
1875/1875 [==============================] - 51s 27ms/step - loss: 0.0613


In [137]:
print("graph");
for i in range(50, 10):
    indice = i;
    plt.imshow(X_test[indice], cmap="gray");
    plt.show()
    
    def getOutput(arr):
        max = 0
        index = 0;
        winner = 0;
        for i in arr[0]:
            i = float(i)
            print("------------- indice:", index, round(i, 4))
            if( i > max ):
                max = i;
                winner = index;
            index += 1;
        return winner
    
    sample = X_test[indice].reshape(-1, 28*28).astype(np.float32)
    print(getOutput(tf.nn.softmax(model.predict(sample))))
    print(y_test[indice])


X_test = X_test.reshape((10000, -1, 28*28))[:, 0, :];
y_t = np.zeros((len(y_test), 10));
for i in range(len(y_test)):
    tmp = np.zeros(10);
    tmp[y_test[i]] = 1;
    y_t[i] = tmp
print(X_test.shape, y_t.shape)
accuracy = model.evaluate(X_test, y_t)
print("Test accuracy:", accuracy)

graph
(10000, 784) (10000, 10)
313/313 [==============================] - 2s 8ms/step - loss: 0.2051
Test accuracy: 0.20507682859897614


In [152]:
# save the model
from pathlib import Path

modelfile = Path().cwd() / 'model.keras';
if(currentDir.exists()):
    res = input("Overwrite the old model? (y/n)");
    if(res == 'y'):
        model.save(modelfile);
    else:
        print("model was not saved");
else:
    model.save(modelfile);

Overwrite the old model? (y/n) y
